# Generated by Django 4.2.1 on 2023-05-09 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Pesion',
            new_name='Persion',
        ),
    ]
