# Generated by Django 4.2.1 on 2023-05-13 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_pesion_persion'),
    ]

    operations = [
        migrations.AddField(
            model_name='persion',
            name='date',
            field=models.DateField(blank=True, default=None),
        ),
    ]
