# Generated by Django 4.2.1 on 2023-05-13 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_persion_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persion',
            name='date',
            field=models.DateTimeField(null=True),
        ),
    ]
