# Generated by Django 4.2.1 on 2023-05-13 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_persion_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='persion',
            name='date',
        ),
        migrations.AddField(
            model_name='cars',
            name='date',
            field=models.TimeField(default=None),
        ),
    ]
