# Generated by Django 4.2.1 on 2023-05-13 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_remove_persion_date_cars_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cars',
            name='date',
        ),
        migrations.AddField(
            model_name='persion',
            name='code_melli',
            field=models.IntegerField(null=True),
        ),
    ]
