# Generated by Django 4.2.1 on 2023-05-13 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_persion_code_melli'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persion',
            name='code_melli',
            field=models.IntegerField(null=True),
        ),
    ]
