# Generated by Django 4.2.1 on 2023-05-13 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_alter_persion_code_melli'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='persion',
            name='code_melli',
        ),
    ]
